#
# Travis CI configuration
#
# @link https://home-assistant.io/docs/ecosystem/backup/backup_github/#step-7-configuration-file-testing
#

language: python

python:
  - 3.7

before_install:
  - mv dummy_secrets.yaml secrets.yaml
  - sudo apt-get install -y libudev-dev

install:
  - pip3 install yamllint
  - pip3 install homeassistant

script:
  - yamllint .
  - hass -c . --script check_config