---
# The configuration.yaml is only used to bootstrap the system.
#
# https://www.home-assistant.io/docs/configuration/basic/
#
homeassistant:
  name: Casa
  unit_system: metric
  time_zone: !secret home_time_zone
  # Load packages
  packages: !include_dir_named integrations

# https://companion.home-assistant.io/en/getting_started/migration#requirements
mobile_app:

# https://www.home-assistant.io/integrations/ssdp/
ssdp:

# https://www.home-assistant.io/integrations/zeroconf/
zeroconf:

# https://www.home-assistant.io/integrations/discovery/
discovery:
  ignore:
    - igd
    - homekit
    - google_cast

# https://www.home-assistant.io/integrations/sensor/
sensor:
  # https://www.home-assistant.io/integrations/google_travel_time/
  - platform: google_travel_time
    name: Home To Work
    api_key: !secret google_distance_matrix_api
    origin: zone.home
    destination: zone.work

# https://www.home-assistant.io/integrations/weather.darksky/
#weather:
#  - platform: darksky
#    api_key: !secret dark_sky_api_key

# https://www.home-assistant.io/integrations/google_assistant/
# google_assistant:

# https://companion.home-assistant.io/en/getting_started/migration#requirements
# ios:

# https://www.home-assistant.io/integrations/cloud/
# cloud:
