---
title: Casa
resources: !include_dir_list lovelace/resources
views:
  - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/living_room.yaml
  - !include lovelace/views/bedroom.yaml
